### PR TITLE
Dockerfile for Gatling 3.2.0

### PR DESCRIPTION
**Pull request by germm**
Dockerfile updated for Gatling 3.2.0

### CODE REVIEW

**Comment by CurlyFire** [comment]
@denvazh Could you approve this pull request and merge ?

**Comment by denvazh** [comment]
@germm Thanks! I was unable to follow-up earlier, but I will merge this PR and also create another one with update to add 3.2.1.

**Comment by CurlyFire** [comment]
Thanks, I copied your dockerfile to upgrade my CI to 3.2.1, but if you do this quickly, I won't have to and just continue using your image.

**Comment by denvazh** [comment]
@CurlyFire I already updated repository to have all versions released so far ( including 3.2.1 ) and also pushed all newly created docker images to docker registry as well.

btw, I also noticed that latest tag there was pointing to the older version, now it points to 3.2.1 (thus `docker pull denvazh/gatling`, `docker pull denvazh/gatling:latest` and `docker pull denvazh/gatling:3.2.1` should have same effect).

**Pull request merged**
